import Link from 'next/link';

const Footer = () => {
  return (
    <footer className="w-full py-8 px-4 mt-auto bg-gray-100">
      <div className="max-w-7xl mx-auto">
        <div className="mb-8 text-sm text-gray-600 space-y-4">
          <p>
            MarketVibe is an educational tool that provides general investment information. The quizzes, results, and investment ideas presented are for informational purposes only and should not be considered as financial advice or investment recommendations. MarketVibe is not a registered investment advisor, broker-dealer, or financial planner.
          </p>
          <p>
            All investments carry risk, including the potential loss of principal. Investment options presented through MarketVibe's quizzes may not be suitable for all investors. Past performance does not guarantee future results.
          </p>
          <p>
            The investment ideas generated by our quizzes are based solely on your quiz responses and should not be considered as personalized investment recommendations. Before making any investment decisions, you should conduct your own research and consult with qualified financial, legal, and tax professionals regarding your specific financial situation, objectives, and risk tolerance.
          </p>
          <p>
            By using MarketVibe, you acknowledge and agree that you are solely responsible for your investment decisions and their outcomes. MarketVibe does not guarantee the accuracy, completeness, or timeliness of any information provided.
          </p>
        </div>
        <div className="pt-6 border-t border-gray-200 flex flex-col sm:flex-row justify-between items-center">
          <div className="mb-4 sm:mb-0">
          <p className="text-sm text-gray-600">© 2025 MarketVibe.app. All rights reserved.</p>
        </div>
          <nav className="flex gap-6">
          <Link 
            href="/privacy-policy" 
            className="text-sm text-gray-600 hover:text-gray-900 transition-colors"
          >
            Privacy Policy
          </Link>
          <Link 
            href="/contact" 
            className="text-sm text-gray-600 hover:text-gray-900 transition-colors"
          >
            Contact
          </Link>
        </nav>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
